ame: 'DotCMS S3 documentation pusher'
description: 'Pushes generated documentation to S3 bucket'
author: 'Victor Alfaro'
inputs:
  aws_access_key_id:
    description: 'AWS access key id'
    required: true
  aws_secret_access_key:
    description: 'AWS secret access key'
    required: true
  dry_run:
    description: 'Dry run mode flag'
    required: false
    default: 'true'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check'
  color: 'blue'